// Regenerates src/components/hairline/generated/ from hairline-figures/: the Hairline kernel
// (taken from any bench page; they all carry the same one) and each figure wrapped as a module.
// Usage: bun scripts/hairline.ts

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";

const SRC = "hairline-figures";
const OUT = "src/components/hairline/generated";
const HEADER = "// Generated by `bun scripts/hairline.ts` from hairline-figures/. Do not edit.\n";

await mkdir(OUT, { recursive: true });

const files = await readdir(SRC);
const bench = await readFile(`${SRC}/${files.find((f) => f.endsWith(".html"))}`, "utf8");
const kernel = bench.match(/<script id="hl-kernel">([\s\S]*?)<\/script>/)?.[1];
if (!kernel) throw new Error("No hl-kernel script found.");
await writeFile(`${OUT}/kernel.js`, `${HEADER}${kernel.trim()}\nexport default HL;\n`);
await writeFile(
  `${OUT}/kernel.d.ts`,
  `${HEADER}// Only what the React wrapper calls; figures get the whole kernel.\n` +
    `declare const HL: {\n` +
    `  inject(root: Document | ShadowRoot): void;\n` +
    `  mk(tag: string, attrs: Record<string, string | number>, parent: Element): Element;\n` +
    `};\nexport default HL;\n`,
);

// A figure reads `HL` and calls `hairline(figure)` as globals; take both as arguments instead.
const names = files.filter((f) => f.endsWith(".js")).map((f) => f.replace(/\.js$/, "")).sort();
for (const name of names) {
  const body = await readFile(`${SRC}/${name}.js`, "utf8");
  await writeFile(`${OUT}/${name}.js`, `${HEADER}export default function define(HL, hairline) {\n${body.trim()}\n}\n`);
}

await writeFile(
  `${OUT}/index.ts`,
  `${HEADER}${names.map((n) => `import ${n} from "./${n}.js";`).join("\n")}\n\n` +
    `export const figures = { ${names.join(", ")} } as const;\n`,
);

// The names alone, so server components can list figures without pulling in the client code.
await writeFile(
  `${OUT}/names.ts`,
  `${HEADER}export const hairlineFigures = [${names.map((n) => `"${n}"`).join(", ")}] as const;\n\n` +
    `export type HairlineFigureName = (typeof hairlineFigures)[number];\n`,
);

console.log(`Wrote kernel and ${names.length} figures: ${names.join(", ")}`);
