// Regenerates src/content/wada.ts from Matt DesLauriers' MIT-licensed digitisation of
// Sanzo Wada's "A Dictionary of Color Combinations".
// Usage: bun scripts/wada.ts

import { writeFile } from "node:fs/promises";

const SOURCE = "https://raw.githubusercontent.com/mattdesl/dictionary-of-colour-combinations/master/colors.json";

type SourceColor = { name: string; hex: string; combinations: number[] };

const source: SourceColor[] = await fetch(SOURCE).then((r) => r.json());

const colorLines = source.map((c) => `  { name: ${JSON.stringify(c.name)}, hex: "${c.hex}" },`);

// Invert colour -> combination membership into combination -> colour indices.
const members = new Map<number, number[]>();
source.forEach((c, index) => {
  for (const id of c.combinations) members.set(id, [...(members.get(id) ?? []), index]);
});
const comboLines = [...members.entries()]
  .sort(([a], [b]) => a - b)
  .map(([id, indices]) => `  [${id}, [${indices.join(", ")}]],`);

const output = `// Generated by scripts/wada.ts. Do not edit by hand.
// Colours and combinations from Sanzo Wada, "A Dictionary of Color Combinations" (1933),
// via https://github.com/mattdesl/dictionary-of-colour-combinations (MIT, Matt DesLauriers).

export type Hex = \`#\${string}\`;

export type WadaColor = { name: string; hex: Hex };

export type Combination = {
  /** Combination number as printed in the book (1 to 348). */
  id: number;
  /** Two to four colours. */
  colors: readonly WadaColor[];
};

export const wadaColors = [
${colorLines.join("\n")}
] as const satisfies readonly WadaColor[];

const raw: readonly (readonly [id: number, colorIndices: readonly number[]])[] = [
${comboLines.join("\n")}
];

export const combinations: readonly Combination[] = raw.map(([id, indices]) => ({
  id,
  colors: indices.map((i) => wadaColors[i]),
}));

const byId = new Map(combinations.map((c) => [c.id, c]));

/** Look up a combination by its book number. Falls back to combination 1 for unknown ids. */
export const getCombination = (id: number): Combination => byId.get(id) ?? combinations[0];
`;

await writeFile(new URL("../src/content/wada.ts", import.meta.url), output);
console.log(`Wrote ${source.length} colours and ${members.size} combinations.`);
